### ISSUE TITLE
Add data logging

### ISSUE THREAD

**Issue by matthew-ia** [TeamSunergy/chase-ui#29]
Use the incoming data to create log files (as `.json`). These files should be able to easily be read in as an object, particularly for a graph to show a certain span of time. 

The format should be something like:
```
{ 
  "Jul 06 2018 08:50:42 AM" : {
    "data_name_0" : "value_0",
    "data_name_1" : "value_1"
  },
  "Jul 09 2018 09:10:39 AM" : {
    "data_name_0" : "value_0",
    "data_name_1" : "value_1"
  }
}
```

**Comment by stevesoaress** [comment]
We can also look at mongoDB to store these files.

**Comment by matthew-ia** [comment]
We can but we don't have much time and I have no familiarity with mongoDB. Would there be a performance benefit?

**Comment by stevesoaress** [comment]
Sorry if I'm mistaken, I thought the telem. apps wouldn't be able to receive data because of the motor controllers. This would only be fixed after the race. Is this not the case?

**Comment by matthew-ia** [comment]
Using the Mitsubas we just won't be getting motor information. We still have the CAN Bus line with the other components sending data.

**Comment by stevesoaress** [comment]
Revisiting - I think we should choose to support a document based database like Mongodb. Messages coming off the queue should be asynchronously written to a document and stored. Advantages include data retrieval for real-time or post-race analysis.

**Comment by stevesoaress** [comment]
This issue was moved to stevesoaress/test#1
